import type { Project } from './types';

export const projects: Project[] = [
  {

    id: '1',
    rank: 1,
    title: 'AI Image Explainability',
    description: 'Built an AI that spots fake images and explains why — even in blurry 32×32 pixels. Combined smart CNNs with a vision-language model to detect artifacts and reveal the truth behind AI-generated visuals.',
    imageUrl: '/images/projects/Ai_explanablilty.png',
    imageHint: 'AI',
    githubLink: 'https://github.com/madhavkataria1010/AI-Image-Explainability',
    tags: ['VLMs', 'GANs', 'KANs', 'VAEs', 'LoRA', 'Knowledge Distillation', 'Diffusion Models'],
  },
  {
    id: '2',
    rank: 2,
    title: 'DeepPlay: Autonomous Football Agents',
    description: 'Leveraged Deep Q-Networks in PyTorch and TensorFlow to train Unity-based football agents from scratch, achieving a 40% boost in strategic decision-making accuracy and an 85% success rate in mastering complex gameplay strategies. A 3D Unity simulation visualizes learned agent behaviors and tactics.',
    imageUrl: '/images/projects/Deep_play.png',
    imageHint: 'team tasks',
    liveLink: 'https://iitjacin-my.sharepoint.com/:v:/g/personal/b23ch1025_iitj_ac_in/EfligOT9Lx5Hv-_ocnB02QUBOBfVAQs8jebLLuMv0SR6_g?e=7QevEw',
    githubLink: 'https://iitjacin-my.sharepoint.com/personal/b23ch1025_iitj_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fb23ch1025%5Fiitj%5Fac%5Fin%2FDocuments%2FSanta%20Project&ga=1',
    tags: ['Unity Engine', 'DQN', 'PPO', 'Blender', 'PyTorch', 'Reinforcement Learning'],
  },
  {
    id: '3',
    rank: 3,
    title: 'AI Agent for Domain-Specific QA',
    description: 'Built a high-efficiency AI agent for domain-specific question answering using GPT-4, combining multi-task learning with prompt engineering and CoT reasoning to streamline support workflows, cut response times, and deliver scalable cost savings.',
    imageUrl: '/images/projects/devrev.png',
    imageHint: 'photo gallery',
    liveLink: 'https://drive.google.com/file/d/1gzoY9JNJnLCivzH_Ew4q74S1LK58HX9P/view?usp=sharing',
    githubLink: 'https://github.com/madhavkataria1010/InterIIT-Devrev',
    tags: ['Prompt engineering', 'CoTs', 'Multi-task learning', 'Model distillation'],
  },

  { id: '4',
    rank: 4,
    title: 'DeepFusion-C',
    description: 'DeepFusion-C is a hand-optimized C implementation of a four-layer CNN for MNIST digit recognition, leveraging SIMD intrinsics and OpenMP to deliver sub-millisecond, >99.2%-accurate inference with detailed latency, throughput and memory profiling.',
    imageUrl: '/images/projects/mnist.png',
    imageHint: 'AI',
    githubLink: 'https://github.com/madhavkataria1010/',
    tags: ['C', 'CNN', 'MNIST', 'Model Adapter', 'Custom IDX-format MNIST loader'],
  },
  // {
  //   id: '5',
  //   rank: 5,
  //   title: 'DeepPlay: Autonomous Football Agents',
  //   description: 'Leveraged Deep Q-Networks in PyTorch and TensorFlow to train Unity-based football agents from scratch, achieving a 40% boost in strategic decision-making accuracy and an 85% success rate in mastering complex gameplay strategies. A 3D Unity simulation visualizes learned agent behaviors and tactics.',
  //   imageUrl: '/images/projects/Deep_play.png',
  //   imageHint: 'team tasks',
  //   liveLink: 'https://iitjacin-my.sharepoint.com/:v:/g/personal/b23ch1025_iitj_ac_in/EfligOT9Lx5Hv-_ocnB02QUBOBfVAQs8jebLLuMv0SR6_g?e=7QevEw',
  //   githubLink: 'https://iitjacin-my.sharepoint.com/personal/b23ch1025_iitj_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fb23ch1025%5Fiitj%5Fac%5Fin%2FDocuments%2FSanta%20Project&ga=1',
  //   tags: ['Unity Engine', 'DQN', 'PPO', 'Blender', 'PyTorch', 'Reinforcement Learning'],
  // },
  // {
  //   id: '6',
  //   rank: 6,
  //   title: 'AI Agent for Domain-Specific QA',
  //   description: 'Built a high-efficiency AI agent for domain-specific question answering using GPT-4, combining multi-task learning with prompt engineering and CoT reasoning to streamline support workflows, cut response times, and deliver scalable cost savings.',
  //   imageUrl: '/images/projects/devrev.png',
  //   imageHint: 'photo gallery',
  //   liveLink: 'https://drive.google.com/file/d/1gzoY9JNJnLCivzH_Ew4q74S1LK58HX9P/view?usp=sharing',
  //   githubLink: 'https://github.com/madhavkataria1010/InterIIT-Devrev',
  //   tags: ['Rrompt engineering', 'CoTs', 'Multi-task learning', 'Model distillation'],
  // },

  //   {
  //   id: '7',
  //   rank: 7,
  //   title: 'DeepPlay: Autonomous Football Agents',
  //   description: 'Leveraged Deep Q-Networks in PyTorch and TensorFlow to train Unity-based football agents from scratch, achieving a 40% boost in strategic decision-making accuracy and an 85% success rate in mastering complex gameplay strategies. A 3D Unity simulation visualizes learned agent behaviors and tactics.',
  //   imageUrl: '/images/projects/Deep_play.png',
  //   imageHint: 'team tasks',
  //   liveLink: 'https://iitjacin-my.sharepoint.com/:v:/g/personal/b23ch1025_iitj_ac_in/EfligOT9Lx5Hv-_ocnB02QUBOBfVAQs8jebLLuMv0SR6_g?e=7QevEw',
  //   githubLink: 'https://iitjacin-my.sharepoint.com/personal/b23ch1025_iitj_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fb23ch1025%5Fiitj%5Fac%5Fin%2FDocuments%2FSanta%20Project&ga=1',
  //   tags: ['Unity Engine', 'DQN', 'PPO', 'Blender', 'PyTorch', 'Reinforcement Learning'],
  // },
  // {
  //   id: '8',
  //   rank: 8,
  //   title: 'AI Agent for Domain-Specific QA',
  //   description: 'Built a high-efficiency AI agent for domain-specific question answering using GPT-4, combining multi-task learning with prompt engineering and CoT reasoning to streamline support workflows, cut response times, and deliver scalable cost savings.',
  //   imageUrl: '/images/projects/devrev.png',
  //   imageHint: 'photo gallery',
  //   liveLink: 'https://drive.google.com/file/d/1gzoY9JNJnLCivzH_Ew4q74S1LK58HX9P/view?usp=sharing',
  //   githubLink: 'https://github.com/madhavkataria1010/InterIIT-Devrev',
  //   tags: ['Rrompt engineering', 'CoTs', 'Multi-task learning', 'Model distillation'],
  // },
];

